### ISSUE TITLE
user cant login when press login button

### ISSUE THREAD

**Issue by babitabhandari** [ionicthemes/google-login-ionic-framework#2]
When I  click to sign with google button it only shows that loggging in... but does not login.The following error occurs

TypeError: Cannot read property 'googleplus' of undefined
    at Scope.$scope.googleSignIn (http://localhost:8100/js/controllers.js:11:19)
    at fn (eval at <anonymous> (http://localhost:8100/lib/ionic/js/ionic.bundle.js:26457:15), <anonymous>:4:227)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:62386:9
    at Scope.$eval (http://localhost:8100/lib/ionic/js/ionic.bundle.js:29158:28)
    at Scope.$apply (http://localhost:8100/lib/ionic/js/ionic.bundle.js:29257:23)
    at HTMLAnchorElement.<anonymous> (http://localhost:8100/lib/ionic/js/ionic.bundle.js:62385:13)
    at HTMLAnchorElement.eventHandler (http://localhost:8100/lib/ionic/js/ionic.bundle.js:16583:21)
    at triggerMouseEvent (http://localhost:8100/lib/ionic/js/ionic.bundle.js:2948:7)
    at tapClick (http://localhost:8100/lib/ionic/js/ionic.bundle.js:2937:3)
    at HTMLDocument.tapMouseUp (http://localhost:8100/lib/ionic/js/ionic.bundle.js:3013:5)

**Comment by Gajendrasinh** [comment]
i am also fetching same error, can you resolved it?

**Comment by djabif** [comment]
Are you running this in a real device or emulator? You have to run it on real device in order to be able to login through your Google account.
Please find the step by step guide and user comments in https://ionicthemes.com/tutorials/about/google-plus-login-with-ionic-framework
